[2024-08-31T19:13:44.099+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-31T19:13:41.489528+00:00 [queued]>
[2024-08-31T19:13:44.115+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-31T19:13:41.489528+00:00 [queued]>
[2024-08-31T19:13:44.116+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-08-31T19:13:44.137+0000] {taskinstance.py:2214} INFO - Executing <Task(SparkSubmitOperator): spark_retail_analysis_task> on 2024-08-31 19:13:41.489528+00:00
[2024-08-31T19:13:44.152+0000] {standard_task_runner.py:60} INFO - Started process 17024 to run task
[2024-08-31T19:13:44.155+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'spark_retail_analysis_dag', 'spark_retail_analysis_task', 'manual__2024-08-31T19:13:41.489528+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/spark_retail_analysis_dag.py', '--cfg-path', '/tmp/tmpy1f7mk3p']
[2024-08-31T19:13:44.158+0000] {standard_task_runner.py:88} INFO - Job 60: Subtask spark_retail_analysis_task
[2024-08-31T19:13:44.182+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-31T19:13:44.233+0000] {task_command.py:423} INFO - Running <TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-31T19:13:41.489528+00:00 [running]> on host dataeng-airflow-scheduler
[2024-08-31T19:13:44.365+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dibimbing' AIRFLOW_CTX_DAG_ID='spark_retail_analysis_dag' AIRFLOW_CTX_TASK_ID='spark_retail_analysis_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-31T19:13:41.489528+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-31T19:13:41.489528+00:00'
[2024-08-31T19:13:44.375+0000] {base.py:83} INFO - Using connection ID 'spark_main' for task execution.
[2024-08-31T19:13:44.380+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://dataeng-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/spark-retail-analysis.py
[2024-08-31T19:13:50.997+0000] {spark_submit.py:579} INFO - :: loading settings :: url = jar:file:/home/airflow/.local/lib/python3.9/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-08-31T19:13:51.101+0000] {spark_submit.py:579} INFO - Ivy Default Cache set to: /home/airflow/.ivy2/cache
[2024-08-31T19:13:51.102+0000] {spark_submit.py:579} INFO - The jars for the packages stored in: /home/airflow/.ivy2/jars
[2024-08-31T19:13:51.109+0000] {spark_submit.py:579} INFO - org.postgresql#postgresql added as a dependency
[2024-08-31T19:13:51.115+0000] {spark_submit.py:579} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-987801ed-3a0f-4b9a-adf5-4f56129b55f9;1.0
[2024-08-31T19:13:51.116+0000] {spark_submit.py:579} INFO - confs: [default]
[2024-08-31T19:13:51.287+0000] {spark_submit.py:579} INFO - found org.postgresql#postgresql;42.2.18 in central
[2024-08-31T19:13:51.330+0000] {spark_submit.py:579} INFO - found org.checkerframework#checker-qual;3.5.0 in central
[2024-08-31T19:13:51.367+0000] {spark_submit.py:579} INFO - :: resolution report :: resolve 241ms :: artifacts dl 14ms
[2024-08-31T19:13:51.368+0000] {spark_submit.py:579} INFO - :: modules in use:
[2024-08-31T19:13:51.369+0000] {spark_submit.py:579} INFO - org.checkerframework#checker-qual;3.5.0 from central in [default]
[2024-08-31T19:13:51.370+0000] {spark_submit.py:579} INFO - org.postgresql#postgresql;42.2.18 from central in [default]
[2024-08-31T19:13:51.371+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-08-31T19:13:51.372+0000] {spark_submit.py:579} INFO - |                  |            modules            ||   artifacts   |
[2024-08-31T19:13:51.373+0000] {spark_submit.py:579} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-08-31T19:13:51.374+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-08-31T19:13:51.377+0000] {spark_submit.py:579} INFO - |      default     |   2   |   0   |   0   |   0   ||   2   |   0   |
[2024-08-31T19:13:51.380+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-08-31T19:13:51.385+0000] {spark_submit.py:579} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-987801ed-3a0f-4b9a-adf5-4f56129b55f9
[2024-08-31T19:13:51.386+0000] {spark_submit.py:579} INFO - confs: [default]
[2024-08-31T19:13:51.401+0000] {spark_submit.py:579} INFO - 0 artifacts copied, 2 already retrieved (0kB/15ms)
[2024-08-31T19:13:51.998+0000] {spark_submit.py:579} INFO - 24/08/31 19:13:51 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-08-31T19:13:54.173+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2024-08-31T19:13:54.174+0000] {spark_submit.py:579} INFO - File "/spark-scripts/spark-retail-analysis.py", line 19, in <module>
[2024-08-31T19:13:54.180+0000] {spark_submit.py:579} INFO - raise ValueError("PostgreSQL environment variables are not all set properly.")
[2024-08-31T19:13:54.181+0000] {spark_submit.py:579} INFO - ValueError: PostgreSQL environment variables are not all set properly.
[2024-08-31T19:13:54.271+0000] {spark_submit.py:579} INFO - 24/08/31 19:13:54 INFO ShutdownHookManager: Shutdown hook called
[2024-08-31T19:13:54.273+0000] {spark_submit.py:579} INFO - 24/08/31 19:13:54 INFO ShutdownHookManager: Deleting directory /tmp/spark-34567a62-0f7f-4bb1-8d72-7bf5e7e9515e
[2024-08-31T19:13:54.366+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://dataeng-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/spark-retail-analysis.py. Error code is: 1.
[2024-08-31T19:13:54.371+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=spark_retail_analysis_dag, task_id=spark_retail_analysis_task, execution_date=20240831T191341, start_date=20240831T191344, end_date=20240831T191354
[2024-08-31T19:13:54.396+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 60 for task spark_retail_analysis_task (Cannot execute: spark-submit --master spark://dataeng-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/spark-retail-analysis.py. Error code is: 1.; 17024)
[2024-08-31T19:13:54.446+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-31T19:13:54.470+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
