[2024-08-31T19:24:08.837+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-31T19:24:06.650865+00:00 [queued]>
[2024-08-31T19:24:08.867+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-31T19:24:06.650865+00:00 [queued]>
[2024-08-31T19:24:08.868+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-08-31T19:24:08.898+0000] {taskinstance.py:2214} INFO - Executing <Task(SparkSubmitOperator): spark_retail_analysis_task> on 2024-08-31 19:24:06.650865+00:00
[2024-08-31T19:24:08.909+0000] {standard_task_runner.py:60} INFO - Started process 17354 to run task
[2024-08-31T19:24:08.917+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'spark_retail_analysis_dag', 'spark_retail_analysis_task', 'manual__2024-08-31T19:24:06.650865+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/spark_retail_analysis_dag.py', '--cfg-path', '/tmp/tmpm5i73waw']
[2024-08-31T19:24:08.933+0000] {standard_task_runner.py:88} INFO - Job 62: Subtask spark_retail_analysis_task
[2024-08-31T19:24:08.985+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-31T19:24:09.105+0000] {task_command.py:423} INFO - Running <TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-31T19:24:06.650865+00:00 [running]> on host dataeng-airflow-scheduler
[2024-08-31T19:24:09.303+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dibimbing' AIRFLOW_CTX_DAG_ID='spark_retail_analysis_dag' AIRFLOW_CTX_TASK_ID='spark_retail_analysis_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-31T19:24:06.650865+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-31T19:24:06.650865+00:00'
[2024-08-31T19:24:09.317+0000] {base.py:83} INFO - Using connection ID 'spark_main' for task execution.
[2024-08-31T19:24:09.319+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://dataeng-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/spark-retail-analysis.py
[2024-08-31T19:24:14.214+0000] {spark_submit.py:579} INFO - :: loading settings :: url = jar:file:/home/airflow/.local/lib/python3.9/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-08-31T19:24:14.456+0000] {spark_submit.py:579} INFO - Ivy Default Cache set to: /home/airflow/.ivy2/cache
[2024-08-31T19:24:14.457+0000] {spark_submit.py:579} INFO - The jars for the packages stored in: /home/airflow/.ivy2/jars
[2024-08-31T19:24:14.502+0000] {spark_submit.py:579} INFO - org.postgresql#postgresql added as a dependency
[2024-08-31T19:24:14.528+0000] {spark_submit.py:579} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-76700e02-bc72-4f88-9f77-437696f5f7fd;1.0
[2024-08-31T19:24:14.539+0000] {spark_submit.py:579} INFO - confs: [default]
[2024-08-31T19:24:14.807+0000] {spark_submit.py:579} INFO - found org.postgresql#postgresql;42.2.18 in central
[2024-08-31T19:24:14.959+0000] {spark_submit.py:579} INFO - found org.checkerframework#checker-qual;3.5.0 in central
[2024-08-31T19:24:15.087+0000] {spark_submit.py:579} INFO - :: resolution report :: resolve 554ms :: artifacts dl 18ms
[2024-08-31T19:24:15.088+0000] {spark_submit.py:579} INFO - :: modules in use:
[2024-08-31T19:24:15.089+0000] {spark_submit.py:579} INFO - org.checkerframework#checker-qual;3.5.0 from central in [default]
[2024-08-31T19:24:15.090+0000] {spark_submit.py:579} INFO - org.postgresql#postgresql;42.2.18 from central in [default]
[2024-08-31T19:24:15.090+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-08-31T19:24:15.091+0000] {spark_submit.py:579} INFO - |                  |            modules            ||   artifacts   |
[2024-08-31T19:24:15.092+0000] {spark_submit.py:579} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-08-31T19:24:15.099+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-08-31T19:24:15.099+0000] {spark_submit.py:579} INFO - |      default     |   2   |   0   |   0   |   0   ||   2   |   0   |
[2024-08-31T19:24:15.100+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-08-31T19:24:15.101+0000] {spark_submit.py:579} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-76700e02-bc72-4f88-9f77-437696f5f7fd
[2024-08-31T19:24:15.102+0000] {spark_submit.py:579} INFO - confs: [default]
[2024-08-31T19:24:15.107+0000] {spark_submit.py:579} INFO - 0 artifacts copied, 2 already retrieved (0kB/18ms)
[2024-08-31T19:24:15.583+0000] {spark_submit.py:579} INFO - 24/08/31 19:24:15 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-08-31T19:24:17.239+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2024-08-31T19:24:17.240+0000] {spark_submit.py:579} INFO - File "/spark-scripts/spark-retail-analysis.py", line 21, in <module>
[2024-08-31T19:24:17.245+0000] {spark_submit.py:579} INFO - raise ValueError("PostgreSQL environment variables are not all set properly.")
[2024-08-31T19:24:17.246+0000] {spark_submit.py:579} INFO - ValueError: PostgreSQL environment variables are not all set properly.
[2024-08-31T19:24:17.322+0000] {spark_submit.py:579} INFO - 24/08/31 19:24:17 INFO ShutdownHookManager: Shutdown hook called
[2024-08-31T19:24:17.328+0000] {spark_submit.py:579} INFO - 24/08/31 19:24:17 INFO ShutdownHookManager: Deleting directory /tmp/spark-81fec0b9-f74a-42ab-9035-60e5721b6b01
[2024-08-31T19:24:17.415+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://dataeng-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/spark-retail-analysis.py. Error code is: 1.
[2024-08-31T19:24:17.421+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=spark_retail_analysis_dag, task_id=spark_retail_analysis_task, execution_date=20240831T192406, start_date=20240831T192408, end_date=20240831T192417
[2024-08-31T19:24:17.447+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 62 for task spark_retail_analysis_task (Cannot execute: spark-submit --master spark://dataeng-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/spark-retail-analysis.py. Error code is: 1.; 17354)
[2024-08-31T19:24:17.492+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-31T19:24:17.515+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
