[2024-09-01T04:29:02.255+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-09-01T04:28:42.364553+00:00 [queued]>
[2024-09-01T04:29:02.294+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-09-01T04:28:42.364553+00:00 [queued]>
[2024-09-01T04:29:02.295+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-09-01T04:29:02.371+0000] {taskinstance.py:2214} INFO - Executing <Task(SparkSubmitOperator): spark_retail_analysis_task> on 2024-09-01 04:28:42.364553+00:00
[2024-09-01T04:29:02.407+0000] {standard_task_runner.py:60} INFO - Started process 3791 to run task
[2024-09-01T04:29:02.432+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'spark_retail_analysis_dag', 'spark_retail_analysis_task', 'manual__2024-09-01T04:28:42.364553+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/spark_retail_analysis_dag.py', '--cfg-path', '/tmp/tmparxjor89']
[2024-09-01T04:29:02.437+0000] {standard_task_runner.py:88} INFO - Job 65: Subtask spark_retail_analysis_task
[2024-09-01T04:29:02.556+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-01T04:29:02.934+0000] {task_command.py:423} INFO - Running <TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-09-01T04:28:42.364553+00:00 [running]> on host dataeng-airflow-scheduler
[2024-09-01T04:29:04.143+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dibimbing' AIRFLOW_CTX_DAG_ID='spark_retail_analysis_dag' AIRFLOW_CTX_TASK_ID='spark_retail_analysis_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-01T04:28:42.364553+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-01T04:28:42.364553+00:00'
[2024-09-01T04:29:04.294+0000] {base.py:83} INFO - Using connection ID 'spark_main' for task execution.
[2024-09-01T04:29:04.329+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://dataeng-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/spark-retail-analysis.py
[2024-09-01T04:29:19.238+0000] {spark_submit.py:579} INFO - :: loading settings :: url = jar:file:/home/airflow/.local/lib/python3.9/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-09-01T04:29:19.705+0000] {spark_submit.py:579} INFO - Ivy Default Cache set to: /home/airflow/.ivy2/cache
[2024-09-01T04:29:19.715+0000] {spark_submit.py:579} INFO - The jars for the packages stored in: /home/airflow/.ivy2/jars
[2024-09-01T04:29:19.741+0000] {spark_submit.py:579} INFO - org.postgresql#postgresql added as a dependency
[2024-09-01T04:29:19.756+0000] {spark_submit.py:579} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-b3596343-12cb-42fa-a527-13098f163cfd;1.0
[2024-09-01T04:29:19.772+0000] {spark_submit.py:579} INFO - confs: [default]
[2024-09-01T04:29:20.295+0000] {spark_submit.py:579} INFO - found org.postgresql#postgresql;42.2.18 in central
[2024-09-01T04:29:20.463+0000] {spark_submit.py:579} INFO - found org.checkerframework#checker-qual;3.5.0 in central
[2024-09-01T04:29:20.525+0000] {spark_submit.py:579} INFO - :: resolution report :: resolve 765ms :: artifacts dl 22ms
[2024-09-01T04:29:20.532+0000] {spark_submit.py:579} INFO - :: modules in use:
[2024-09-01T04:29:20.538+0000] {spark_submit.py:579} INFO - org.checkerframework#checker-qual;3.5.0 from central in [default]
[2024-09-01T04:29:20.542+0000] {spark_submit.py:579} INFO - org.postgresql#postgresql;42.2.18 from central in [default]
[2024-09-01T04:29:20.543+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-09-01T04:29:20.544+0000] {spark_submit.py:579} INFO - |                  |            modules            ||   artifacts   |
[2024-09-01T04:29:20.546+0000] {spark_submit.py:579} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-09-01T04:29:20.546+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-09-01T04:29:20.547+0000] {spark_submit.py:579} INFO - |      default     |   2   |   0   |   0   |   0   ||   2   |   0   |
[2024-09-01T04:29:20.548+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-09-01T04:29:20.560+0000] {spark_submit.py:579} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-b3596343-12cb-42fa-a527-13098f163cfd
[2024-09-01T04:29:20.562+0000] {spark_submit.py:579} INFO - confs: [default]
[2024-09-01T04:29:20.582+0000] {spark_submit.py:579} INFO - 0 artifacts copied, 2 already retrieved (0kB/20ms)
[2024-09-01T04:29:22.734+0000] {spark_submit.py:579} INFO - 24/09/01 04:29:22 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-09-01T04:29:26.954+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2024-09-01T04:29:26.956+0000] {spark_submit.py:579} INFO - File "/spark-scripts/spark-retail-analysis.py", line 20, in <module>
[2024-09-01T04:29:26.958+0000] {spark_submit.py:579} INFO - raise ValueError("PostgreSQL environment variables are not all set properly.")
[2024-09-01T04:29:26.962+0000] {spark_submit.py:579} INFO - ValueError: PostgreSQL environment variables are not all set properly.
[2024-09-01T04:29:27.140+0000] {spark_submit.py:579} INFO - 24/09/01 04:29:27 INFO ShutdownHookManager: Shutdown hook called
[2024-09-01T04:29:27.148+0000] {spark_submit.py:579} INFO - 24/09/01 04:29:27 INFO ShutdownHookManager: Deleting directory /tmp/spark-b8c92876-478a-4615-8a49-ad206fc138b2
[2024-09-01T04:29:27.372+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://dataeng-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/spark-retail-analysis.py. Error code is: 1.
[2024-09-01T04:29:27.414+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=spark_retail_analysis_dag, task_id=spark_retail_analysis_task, execution_date=20240901T042842, start_date=20240901T042902, end_date=20240901T042927
[2024-09-01T04:29:27.488+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 65 for task spark_retail_analysis_task (Cannot execute: spark-submit --master spark://dataeng-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/spark-retail-analysis.py. Error code is: 1.; 3791)
[2024-09-01T04:29:27.531+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-09-01T04:29:27.569+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
