[2024-09-01T06:04:40.602+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-09-01T06:02:48.004157+00:00 [queued]>
[2024-09-01T06:04:42.849+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-09-01T06:02:48.004157+00:00 [queued]>
[2024-09-01T06:04:42.885+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-09-01T06:04:46.195+0000] {taskinstance.py:2214} INFO - Executing <Task(SparkSubmitOperator): spark_retail_analysis_task> on 2024-09-01 06:02:48.004157+00:00
[2024-09-01T06:04:47.762+0000] {standard_task_runner.py:60} INFO - Started process 5534 to run task
[2024-09-01T06:04:49.639+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'spark_retail_analysis_dag', 'spark_retail_analysis_task', 'manual__2024-09-01T06:02:48.004157+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/spark_retail_analysis_dag.py', '--cfg-path', '/tmp/tmp_xffdo00']
[2024-09-01T06:04:50.204+0000] {standard_task_runner.py:88} INFO - Job 68: Subtask spark_retail_analysis_task
[2024-09-01T06:05:00.123+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-01T06:05:05.486+0000] {task_command.py:423} INFO - Running <TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-09-01T06:02:48.004157+00:00 [running]> on host dataeng-airflow-scheduler
[2024-09-01T06:05:08.416+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dibimbing' AIRFLOW_CTX_DAG_ID='spark_retail_analysis_dag' AIRFLOW_CTX_TASK_ID='spark_retail_analysis_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-01T06:02:48.004157+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-01T06:02:48.004157+00:00'
[2024-09-01T06:05:08.474+0000] {base.py:83} INFO - Using connection ID 'spark_main' for task execution.
[2024-09-01T06:05:08.479+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://dataeng-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/spark-retail-analysis.py
[2024-09-01T06:06:16.834+0000] {spark_submit.py:579} INFO - :: loading settings :: url = jar:file:/home/airflow/.local/lib/python3.9/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-09-01T06:06:19.489+0000] {spark_submit.py:579} INFO - Ivy Default Cache set to: /home/airflow/.ivy2/cache
[2024-09-01T06:06:19.498+0000] {spark_submit.py:579} INFO - The jars for the packages stored in: /home/airflow/.ivy2/jars
[2024-09-01T06:06:19.588+0000] {spark_submit.py:579} INFO - org.postgresql#postgresql added as a dependency
[2024-09-01T06:06:19.603+0000] {spark_submit.py:579} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-96e87466-00b8-4acc-811f-4df939c23913;1.0
[2024-09-01T06:06:19.630+0000] {spark_submit.py:579} INFO - confs: [default]
[2024-09-01T06:06:29.859+0000] {spark_submit.py:579} INFO - found org.postgresql#postgresql;42.2.18 in central
[2024-09-01T06:06:32.376+0000] {spark_submit.py:579} INFO - found org.checkerframework#checker-qual;3.5.0 in central
[2024-09-01T06:06:33.235+0000] {spark_submit.py:579} INFO - :: resolution report :: resolve 13567ms :: artifacts dl 66ms
[2024-09-01T06:06:33.264+0000] {spark_submit.py:579} INFO - :: modules in use:
[2024-09-01T06:06:33.266+0000] {spark_submit.py:579} INFO - org.checkerframework#checker-qual;3.5.0 from central in [default]
[2024-09-01T06:06:33.272+0000] {spark_submit.py:579} INFO - org.postgresql#postgresql;42.2.18 from central in [default]
[2024-09-01T06:06:33.281+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-09-01T06:06:33.282+0000] {spark_submit.py:579} INFO - |                  |            modules            ||   artifacts   |
[2024-09-01T06:06:33.301+0000] {spark_submit.py:579} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-09-01T06:06:33.305+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-09-01T06:06:33.309+0000] {spark_submit.py:579} INFO - |      default     |   2   |   0   |   0   |   0   ||   2   |   0   |
[2024-09-01T06:06:33.352+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-09-01T06:06:33.366+0000] {spark_submit.py:579} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-96e87466-00b8-4acc-811f-4df939c23913
[2024-09-01T06:06:33.379+0000] {spark_submit.py:579} INFO - confs: [default]
[2024-09-01T06:06:33.385+0000] {spark_submit.py:579} INFO - 0 artifacts copied, 2 already retrieved (0kB/41ms)
[2024-09-01T06:06:36.343+0000] {spark_submit.py:579} INFO - 24/09/01 06:06:36 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-09-01T06:06:54.175+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2024-09-01T06:06:54.178+0000] {spark_submit.py:579} INFO - File "/spark-scripts/spark-retail-analysis.py", line 20, in <module>
[2024-09-01T06:06:54.191+0000] {spark_submit.py:579} INFO - raise ValueError("PostgreSQL environment variables are not all set properly.")
[2024-09-01T06:06:54.211+0000] {spark_submit.py:579} INFO - ValueError: PostgreSQL environment variables are not all set properly.
[2024-09-01T06:06:54.590+0000] {spark_submit.py:579} INFO - 24/09/01 06:06:54 INFO ShutdownHookManager: Shutdown hook called
[2024-09-01T06:06:54.609+0000] {spark_submit.py:579} INFO - 24/09/01 06:06:54 INFO ShutdownHookManager: Deleting directory /tmp/spark-4b7fc6af-d65e-4d73-aaa7-0cce121fde23
[2024-09-01T06:06:54.955+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://dataeng-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/spark-retail-analysis.py. Error code is: 1.
[2024-09-01T06:06:55.103+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=spark_retail_analysis_dag, task_id=spark_retail_analysis_task, execution_date=20240901T060248, start_date=20240901T060440, end_date=20240901T060655
[2024-09-01T06:06:55.208+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 68 for task spark_retail_analysis_task (Cannot execute: spark-submit --master spark://dataeng-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/spark-retail-analysis.py. Error code is: 1.; 5534)
[2024-09-01T06:06:55.291+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-09-01T06:06:56.033+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
