[2024-08-31T18:36:04.672+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-31T18:36:00.181652+00:00 [queued]>
[2024-08-31T18:36:04.712+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-31T18:36:00.181652+00:00 [queued]>
[2024-08-31T18:36:04.713+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-08-31T18:36:04.782+0000] {taskinstance.py:2214} INFO - Executing <Task(SparkSubmitOperator): spark_retail_analysis_task> on 2024-08-31 18:36:00.181652+00:00
[2024-08-31T18:36:04.815+0000] {standard_task_runner.py:60} INFO - Started process 15826 to run task
[2024-08-31T18:36:04.846+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'spark_retail_analysis_dag', 'spark_retail_analysis_task', 'manual__2024-08-31T18:36:00.181652+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/spark_retail_analysis_dag.py', '--cfg-path', '/tmp/tmp4nxqdxus']
[2024-08-31T18:36:04.849+0000] {standard_task_runner.py:88} INFO - Job 55: Subtask spark_retail_analysis_task
[2024-08-31T18:36:04.896+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-31T18:36:05.179+0000] {task_command.py:423} INFO - Running <TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-31T18:36:00.181652+00:00 [running]> on host dataeng-airflow-scheduler
[2024-08-31T18:36:05.751+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dibimbing' AIRFLOW_CTX_DAG_ID='spark_retail_analysis_dag' AIRFLOW_CTX_TASK_ID='spark_retail_analysis_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-31T18:36:00.181652+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-31T18:36:00.181652+00:00'
[2024-08-31T18:36:05.777+0000] {base.py:83} INFO - Using connection ID 'spark_main' for task execution.
[2024-08-31T18:36:05.779+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://dataeng-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/spark-retail-analysis.py
[2024-08-31T18:36:16.931+0000] {spark_submit.py:579} INFO - :: loading settings :: url = jar:file:/home/airflow/.local/lib/python3.9/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-08-31T18:36:17.233+0000] {spark_submit.py:579} INFO - Ivy Default Cache set to: /home/airflow/.ivy2/cache
[2024-08-31T18:36:17.233+0000] {spark_submit.py:579} INFO - The jars for the packages stored in: /home/airflow/.ivy2/jars
[2024-08-31T18:36:17.251+0000] {spark_submit.py:579} INFO - org.postgresql#postgresql added as a dependency
[2024-08-31T18:36:17.252+0000] {spark_submit.py:579} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-b070fb0f-6aa6-44ae-802a-af0a8ef66d0f;1.0
[2024-08-31T18:36:17.255+0000] {spark_submit.py:579} INFO - confs: [default]
[2024-08-31T18:36:17.647+0000] {spark_submit.py:579} INFO - found org.postgresql#postgresql;42.2.18 in central
[2024-08-31T18:36:17.742+0000] {spark_submit.py:579} INFO - found org.checkerframework#checker-qual;3.5.0 in central
[2024-08-31T18:36:17.813+0000] {spark_submit.py:579} INFO - :: resolution report :: resolve 526ms :: artifacts dl 37ms
[2024-08-31T18:36:17.827+0000] {spark_submit.py:579} INFO - :: modules in use:
[2024-08-31T18:36:17.830+0000] {spark_submit.py:579} INFO - org.checkerframework#checker-qual;3.5.0 from central in [default]
[2024-08-31T18:36:17.831+0000] {spark_submit.py:579} INFO - org.postgresql#postgresql;42.2.18 from central in [default]
[2024-08-31T18:36:17.832+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-08-31T18:36:17.833+0000] {spark_submit.py:579} INFO - |                  |            modules            ||   artifacts   |
[2024-08-31T18:36:17.847+0000] {spark_submit.py:579} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-08-31T18:36:17.850+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-08-31T18:36:17.851+0000] {spark_submit.py:579} INFO - |      default     |   2   |   0   |   0   |   0   ||   2   |   0   |
[2024-08-31T18:36:17.852+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-08-31T18:36:17.860+0000] {spark_submit.py:579} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-b070fb0f-6aa6-44ae-802a-af0a8ef66d0f
[2024-08-31T18:36:17.867+0000] {spark_submit.py:579} INFO - confs: [default]
[2024-08-31T18:36:17.894+0000] {spark_submit.py:579} INFO - 0 artifacts copied, 2 already retrieved (0kB/27ms)
[2024-08-31T18:36:20.929+0000] {spark_submit.py:579} INFO - 24/08/31 18:36:20 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-08-31T18:36:25.281+0000] {spark_submit.py:579} INFO - Error reading data from PostgreSQL: name 'spark' is not defined
[2024-08-31T18:36:25.307+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2024-08-31T18:36:25.324+0000] {spark_submit.py:579} INFO - File "/spark-scripts/spark-retail-analysis.py", line 29, in <module>
[2024-08-31T18:36:25.329+0000] {spark_submit.py:579} INFO - retail_df = spark.read.jdbc(
[2024-08-31T18:36:25.331+0000] {spark_submit.py:579} INFO - NameError: name 'spark' is not defined
[2024-08-31T18:36:25.438+0000] {spark_submit.py:579} INFO - 24/08/31 18:36:25 INFO ShutdownHookManager: Shutdown hook called
[2024-08-31T18:36:25.455+0000] {spark_submit.py:579} INFO - 24/08/31 18:36:25 INFO ShutdownHookManager: Deleting directory /tmp/spark-7bc30ef9-f36d-4fea-84f4-0f7fc86e1eb9
[2024-08-31T18:36:25.623+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://dataeng-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/spark-retail-analysis.py. Error code is: 1.
[2024-08-31T18:36:25.642+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=spark_retail_analysis_dag, task_id=spark_retail_analysis_task, execution_date=20240831T183600, start_date=20240831T183604, end_date=20240831T183625
[2024-08-31T18:36:25.686+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 55 for task spark_retail_analysis_task (Cannot execute: spark-submit --master spark://dataeng-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/spark-retail-analysis.py. Error code is: 1.; 15826)
[2024-08-31T18:36:25.739+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-31T18:36:25.789+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
