[2024-08-31T19:09:58.158+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-31T19:09:54.650786+00:00 [queued]>
[2024-08-31T19:09:58.195+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-31T19:09:54.650786+00:00 [queued]>
[2024-08-31T19:09:58.196+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-08-31T19:09:58.237+0000] {taskinstance.py:2214} INFO - Executing <Task(SparkSubmitOperator): spark_retail_analysis_task> on 2024-08-31 19:09:54.650786+00:00
[2024-08-31T19:09:58.246+0000] {standard_task_runner.py:60} INFO - Started process 16894 to run task
[2024-08-31T19:09:58.253+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'spark_retail_analysis_dag', 'spark_retail_analysis_task', 'manual__2024-08-31T19:09:54.650786+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/spark_retail_analysis_dag.py', '--cfg-path', '/tmp/tmpfsrakz3v']
[2024-08-31T19:09:58.256+0000] {standard_task_runner.py:88} INFO - Job 59: Subtask spark_retail_analysis_task
[2024-08-31T19:09:58.294+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-31T19:09:58.396+0000] {task_command.py:423} INFO - Running <TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-31T19:09:54.650786+00:00 [running]> on host dataeng-airflow-scheduler
[2024-08-31T19:09:58.727+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dibimbing' AIRFLOW_CTX_DAG_ID='spark_retail_analysis_dag' AIRFLOW_CTX_TASK_ID='spark_retail_analysis_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-31T19:09:54.650786+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-31T19:09:54.650786+00:00'
[2024-08-31T19:09:58.748+0000] {base.py:83} INFO - Using connection ID 'spark_main' for task execution.
[2024-08-31T19:09:58.753+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://dataeng-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/spark-retail-analysis.py
[2024-08-31T19:10:07.978+0000] {spark_submit.py:579} INFO - :: loading settings :: url = jar:file:/home/airflow/.local/lib/python3.9/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-08-31T19:10:08.142+0000] {spark_submit.py:579} INFO - Ivy Default Cache set to: /home/airflow/.ivy2/cache
[2024-08-31T19:10:08.144+0000] {spark_submit.py:579} INFO - The jars for the packages stored in: /home/airflow/.ivy2/jars
[2024-08-31T19:10:08.155+0000] {spark_submit.py:579} INFO - org.postgresql#postgresql added as a dependency
[2024-08-31T19:10:08.158+0000] {spark_submit.py:579} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-fd4a21ad-a0f7-4e08-bf6a-5a1e3cb1904d;1.0
[2024-08-31T19:10:08.159+0000] {spark_submit.py:579} INFO - confs: [default]
[2024-08-31T19:10:08.506+0000] {spark_submit.py:579} INFO - found org.postgresql#postgresql;42.2.18 in central
[2024-08-31T19:10:08.610+0000] {spark_submit.py:579} INFO - found org.checkerframework#checker-qual;3.5.0 in central
[2024-08-31T19:10:08.771+0000] {spark_submit.py:579} INFO - :: resolution report :: resolve 555ms :: artifacts dl 56ms
[2024-08-31T19:10:08.796+0000] {spark_submit.py:579} INFO - :: modules in use:
[2024-08-31T19:10:08.801+0000] {spark_submit.py:579} INFO - org.checkerframework#checker-qual;3.5.0 from central in [default]
[2024-08-31T19:10:08.812+0000] {spark_submit.py:579} INFO - org.postgresql#postgresql;42.2.18 from central in [default]
[2024-08-31T19:10:08.817+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-08-31T19:10:08.876+0000] {spark_submit.py:579} INFO - |                  |            modules            ||   artifacts   |
[2024-08-31T19:10:08.892+0000] {spark_submit.py:579} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-08-31T19:10:08.908+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-08-31T19:10:08.921+0000] {spark_submit.py:579} INFO - |      default     |   2   |   0   |   0   |   0   ||   2   |   0   |
[2024-08-31T19:10:08.930+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-08-31T19:10:08.936+0000] {spark_submit.py:579} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-fd4a21ad-a0f7-4e08-bf6a-5a1e3cb1904d
[2024-08-31T19:10:08.945+0000] {spark_submit.py:579} INFO - confs: [default]
[2024-08-31T19:10:08.962+0000] {spark_submit.py:579} INFO - 0 artifacts copied, 2 already retrieved (0kB/51ms)
[2024-08-31T19:10:09.845+0000] {spark_submit.py:579} INFO - 24/08/31 19:10:09 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-08-31T19:10:12.529+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2024-08-31T19:10:12.530+0000] {spark_submit.py:579} INFO - File "/spark-scripts/spark-retail-analysis.py", line 19, in <module>
[2024-08-31T19:10:12.536+0000] {spark_submit.py:579} INFO - raise ValueError("PostgreSQL environment variables are not all set properly.")
[2024-08-31T19:10:12.536+0000] {spark_submit.py:579} INFO - ValueError: PostgreSQL environment variables are not all set properly.
[2024-08-31T19:10:12.628+0000] {spark_submit.py:579} INFO - 24/08/31 19:10:12 INFO ShutdownHookManager: Shutdown hook called
[2024-08-31T19:10:12.633+0000] {spark_submit.py:579} INFO - 24/08/31 19:10:12 INFO ShutdownHookManager: Deleting directory /tmp/spark-f1eeb067-495e-44f5-a895-cffc75ee7612
[2024-08-31T19:10:12.721+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://dataeng-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/spark-retail-analysis.py. Error code is: 1.
[2024-08-31T19:10:12.731+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=spark_retail_analysis_dag, task_id=spark_retail_analysis_task, execution_date=20240831T190954, start_date=20240831T190958, end_date=20240831T191012
[2024-08-31T19:10:12.759+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 59 for task spark_retail_analysis_task (Cannot execute: spark-submit --master spark://dataeng-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/spark-retail-analysis.py. Error code is: 1.; 16894)
[2024-08-31T19:10:12.805+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-31T19:10:12.834+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
