[2024-08-31T19:21:14.713+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-31T19:21:11.022670+00:00 [queued]>
[2024-08-31T19:21:14.750+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-31T19:21:11.022670+00:00 [queued]>
[2024-08-31T19:21:14.752+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-08-31T19:21:14.805+0000] {taskinstance.py:2214} INFO - Executing <Task(SparkSubmitOperator): spark_retail_analysis_task> on 2024-08-31 19:21:11.022670+00:00
[2024-08-31T19:21:14.838+0000] {standard_task_runner.py:60} INFO - Started process 17234 to run task
[2024-08-31T19:21:14.852+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'spark_retail_analysis_dag', 'spark_retail_analysis_task', 'manual__2024-08-31T19:21:11.022670+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/spark_retail_analysis_dag.py', '--cfg-path', '/tmp/tmpulk0tvmt']
[2024-08-31T19:21:14.865+0000] {standard_task_runner.py:88} INFO - Job 61: Subtask spark_retail_analysis_task
[2024-08-31T19:21:14.909+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-08-31T19:21:15.064+0000] {task_command.py:423} INFO - Running <TaskInstance: spark_retail_analysis_dag.spark_retail_analysis_task manual__2024-08-31T19:21:11.022670+00:00 [running]> on host dataeng-airflow-scheduler
[2024-08-31T19:21:15.487+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dibimbing' AIRFLOW_CTX_DAG_ID='spark_retail_analysis_dag' AIRFLOW_CTX_TASK_ID='spark_retail_analysis_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-31T19:21:11.022670+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-31T19:21:11.022670+00:00'
[2024-08-31T19:21:15.523+0000] {base.py:83} INFO - Using connection ID 'spark_main' for task execution.
[2024-08-31T19:21:15.532+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://dataeng-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/spark-retail-analysis.py
[2024-08-31T19:21:23.123+0000] {spark_submit.py:579} INFO - :: loading settings :: url = jar:file:/home/airflow/.local/lib/python3.9/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-08-31T19:21:23.299+0000] {spark_submit.py:579} INFO - Ivy Default Cache set to: /home/airflow/.ivy2/cache
[2024-08-31T19:21:23.300+0000] {spark_submit.py:579} INFO - The jars for the packages stored in: /home/airflow/.ivy2/jars
[2024-08-31T19:21:23.316+0000] {spark_submit.py:579} INFO - org.postgresql#postgresql added as a dependency
[2024-08-31T19:21:23.324+0000] {spark_submit.py:579} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-bb246bd8-211c-4686-a831-da5437f0c559;1.0
[2024-08-31T19:21:23.326+0000] {spark_submit.py:579} INFO - confs: [default]
[2024-08-31T19:21:23.701+0000] {spark_submit.py:579} INFO - found org.postgresql#postgresql;42.2.18 in central
[2024-08-31T19:21:23.767+0000] {spark_submit.py:579} INFO - found org.checkerframework#checker-qual;3.5.0 in central
[2024-08-31T19:21:23.820+0000] {spark_submit.py:579} INFO - :: resolution report :: resolve 494ms :: artifacts dl 8ms
[2024-08-31T19:21:23.824+0000] {spark_submit.py:579} INFO - :: modules in use:
[2024-08-31T19:21:23.825+0000] {spark_submit.py:579} INFO - org.checkerframework#checker-qual;3.5.0 from central in [default]
[2024-08-31T19:21:23.828+0000] {spark_submit.py:579} INFO - org.postgresql#postgresql;42.2.18 from central in [default]
[2024-08-31T19:21:23.829+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-08-31T19:21:23.830+0000] {spark_submit.py:579} INFO - |                  |            modules            ||   artifacts   |
[2024-08-31T19:21:23.830+0000] {spark_submit.py:579} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-08-31T19:21:23.831+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-08-31T19:21:23.831+0000] {spark_submit.py:579} INFO - |      default     |   2   |   0   |   0   |   0   ||   2   |   0   |
[2024-08-31T19:21:23.832+0000] {spark_submit.py:579} INFO - ---------------------------------------------------------------------
[2024-08-31T19:21:23.837+0000] {spark_submit.py:579} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-bb246bd8-211c-4686-a831-da5437f0c559
[2024-08-31T19:21:23.845+0000] {spark_submit.py:579} INFO - confs: [default]
[2024-08-31T19:21:23.852+0000] {spark_submit.py:579} INFO - 0 artifacts copied, 2 already retrieved (0kB/14ms)
[2024-08-31T19:21:24.699+0000] {spark_submit.py:579} INFO - 24/08/31 19:21:24 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-08-31T19:21:28.087+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2024-08-31T19:21:28.087+0000] {spark_submit.py:579} INFO - File "/spark-scripts/spark-retail-analysis.py", line 21, in <module>
[2024-08-31T19:21:28.100+0000] {spark_submit.py:579} INFO - raise ValueError("PostgreSQL environment variables are not all set properly.")
[2024-08-31T19:21:28.101+0000] {spark_submit.py:579} INFO - ValueError: PostgreSQL environment variables are not all set properly.
[2024-08-31T19:21:28.222+0000] {spark_submit.py:579} INFO - 24/08/31 19:21:28 INFO ShutdownHookManager: Shutdown hook called
[2024-08-31T19:21:28.227+0000] {spark_submit.py:579} INFO - 24/08/31 19:21:28 INFO ShutdownHookManager: Deleting directory /tmp/spark-29a43fbd-1923-4422-8d20-dc223d66b775
[2024-08-31T19:21:28.402+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://dataeng-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/spark-retail-analysis.py. Error code is: 1.
[2024-08-31T19:21:28.415+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=spark_retail_analysis_dag, task_id=spark_retail_analysis_task, execution_date=20240831T192111, start_date=20240831T192114, end_date=20240831T192128
[2024-08-31T19:21:28.450+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 61 for task spark_retail_analysis_task (Cannot execute: spark-submit --master spark://dataeng-spark-master:7077 --packages org.postgresql:postgresql:42.2.18 --name arrow-spark /spark-scripts/spark-retail-analysis.py. Error code is: 1.; 17234)
[2024-08-31T19:21:28.491+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-31T19:21:28.517+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
